version: "3"

services:
  freshrss:
    image: freshrss/freshrss:latest
    ports:
      - "8080:80"
    hostname: freshrss
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: America/Los_Angeles
      CRON_MIN: '1, 31'
volumes:
  data:
  extensions:
